Let user specify machine-labels
rh-mobb/helm-charts pull request #65
Opened 2023-09-03 13:46 UTC by davidkarlsen

Fixes #64

2023-09-05 17:44 UTC, paulczar requested changes

2023-09-05 17:44 UTC, paulczar commented on charts/aro-machinesets/values.yaml
>  machineTaints:
should we clear this taint too ?

2023-09-05 17:45 UTC, paulczar requested changes
The following doc relies on these defaults.  Can you PR it to override the machineLabels and machineTaints appropriately ?  That way we don't break the doc with this change.

https://mobb.ninja/docs/aro/add-infra-nodes/
https://github.com/rh-mobb/documentation/blob/main/content/docs/aro/add-infra-nodes/index.md

2023-09-06 10:56 UTC, davidkarlsen commented on charts/aro-machinesets/values.yaml
>  machineTaints:
ofc - fixed

2023-09-06 11:06 UTC, davidkarlsen commented
> The following doc relies on these defaults. Can you PR it to override the machineLabels and machineTaints appropriately ? That way we don't break the doc with this change.
> 
> https://mobb.ninja/docs/aro/add-infra-nodes/ https://github.com/rh-mobb/documentation/blob/main/content/docs/aro/add-infra-nodes/index.md

Good catch - see separate PR.

2023-09-06 18:27 UTC, merged